### ISSUE TITLE
Zoom issue

### ISSUE THREAD

**Issue by KimWahlman** [Sightburner/FameAndPrestige#5]
Player can get cards that are zoomed more than they should.
The zoom can be wrong on the playfield as well.

**Comment by Abelarm** [comment]
I didn't understand this could you explain it better?

**Comment by KimWahlman** [comment]
The card are not the correct size on the play field. They will be a lot bigger than they should sometimes.

**Comment by Abelarm** [comment]
Solved with 5a6c0eb
